{
 "title": "Armiarma Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Crawler", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Observed Distribution",
   "type": "timeseries",
   "description": "Client distribution observed by the tool crawling the Eth2 Beaconchain network",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Peers" } },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution"
    }
   ]
  },
  {
   "title": "Current Client Share",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total active nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (crawler_observed_client_distribution)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "targets": [
    { "expr": "host_connected_peers", "legendFormat": "__auto" }
   ]
  },
  { "title": "GossipSub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Peers per GossipSub Topics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 12 },
   "targets": [
    { "expr": "gossipsub_peers_per_topic", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current peers per topic",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 12 },
   "targets": [
    { "expr": "gossipsub_peers_per_topic", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peers per topic Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "targets": [
    { "expr": "gossipsub_peers_per_topic", "legendFormat": "__auto" }
   ]
  },
  { "title": "Crawler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Client Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Version Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "crawler_observed_client_version_distribution",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Popular Client Versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 22 },
   "targets": [
    {
     "expr": "crawler_observed_client_version_distribution",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Active Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(instance) (crawler_observed_client_distribution)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Node Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 32 },
   "targets": [
    { "expr": "crawler_node_distribution", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Geo distribution",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 32 },
   "targets": [
    {
     "expr": "crawler_geographical_distribution",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Peering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Attempted To Connect peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "peering_peers_attempted_last_iteration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iteration Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "peering_peerstore_iteration_time_secs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attempted Peers Distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "peering_iteration_attempts_by_category_distribution",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Error Category Distribution ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "peering_pruned_error_distribution",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Peer Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Attnets Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "discovery_attnets_distribution{att_number!=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "discovery_node_per_fork_distribution",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Allocated Memory Bytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"armiarma\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "go_threads{job=\"armiarma\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}