{
 "title": "Armiarma",
 "description": "Armiarma Eth2 network monitoring tools' dashboard ",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Client Geographical Disrtibution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "expr": "crawler_geographical_distribution{}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "topk(11, crawler_geographical_distribution{country!=\"--\"})"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,crawler_geographical_distribution{country!=\"--\"})",
     "legendFormat": "{{country}}"
    }
   ]
  },
  { "title": "Client Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Client Observed Distribution",
   "type": "graph",
   "description": "Client distribution observed by the tool crawling the Eth2 Beaconchain network",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Peers" } },
   "yaxes": [
    { "format": "Peers" }
   ],
   "targets": [
    {
     "expr": "crawler_observed_client_distribution"
    }
   ]
  },
  {
   "title": "Current Observed Client Distribution (%)",
   "type": "piechart",
   "description": "Client distribution observed by the tool crawling the Eth2 Beaconchain network",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Peers" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution"
    }
   ]
  },
  { "title": "Peers Interaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total Active Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crawler_connected_peers" }
   ]
  },
  {
   "title": "Total Discovered Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crawler_total_crawled_peers{}" }
   ]
  },
  {
   "title": "Total Deprecated Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crawler_deprecated_peers" }
   ]
  },
  { "title": "Network Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "RTT Distribution",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "crawler_observed_rtt_distribution{}",
     "legendFormat": "{{secs}}"
    }
   ]
  },
  {
   "title": "IP Distribution",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "crawler_observed_ip_distribution{}",
     "legendFormat": "{{secs}}"
    }
   ]
  },
  { "title": "GossipSub Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Message/Second/Topic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{topic=\"beacon_aggregate_and_proof\"}"
    }
   ]
  },
  {
   "title": "Message/Second/Topic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{topic=\"beacon_block\"}"
    }
   ]
  },
  {
   "title": "Total Received Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "crawler_total_received_messages_psec"
    }
   ]
  },
  {
   "title": "Received Messages Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_received_messages_psec{}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}