{
 "title": "Armiarma",
 "description": "Armiarma Eth2 network monitoring tools' dashboard ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Client Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Observed Distribution",
   "type": "timeseries",
   "description": "Client distribution observed by the tool crawling the Eth2 Beaconchain network",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Peers" } },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution"
    }
   ]
  },
  {
   "title": "Current Observed Client Distribution (%)",
   "type": "piechart",
   "description": "Client distribution observed by the tool crawling the Eth2 Beaconchain network",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Peers" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution"
    }
   ]
  },
  { "title": "Tool Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Tools' Memory Heap ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes" }
   ]
  },
  {
   "title": "OS Memory Heap ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_sys_bytes" }
   ]
  }
 ]
}